// Titles/designations available for evaluated personnel and system users.
export const PERSON_TITLES = [
  "Mr",
  "Mrs",
  "Miss",
  "Dr",
  "Prof",
  "Air CraftMan",
  "Air Craftwoman",
  "Lance Corporal",
  "Corporal",
  "Sergeant",
  "Flight Sergeant",
  "Warrant Officer",
  "Master Warrant Officer",
  "Air Warrant Officer",
  "Flying Officer",
  "Flight Lieutenant",
  "Squadron Leader",
  "Wing Commander",
  "Group Captain",
  "Air Commodore",
  "Air Vice Marshal",
  "Vice Marshal",
  "Air Chief Marshal",
  "Marshal of the Air Force",
  "Other",
];
